sudo: false
language: node_js
node_js:
  - "7.9"
os:
  - osx
  - linux
addons:
  ssh_known_hosts:
  - github.com
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - yarn install
script:
  - yarn run lint
  - yarn run test:unit
  - yarn run test:integration
  - yarn run test:scenario
notifications:
  email:
    on_success: change
    on_failure: always
