sudo: false
language: node_js
node_js:
  - "12.18.3"
os:
  - osx
install:
  - yarn install
script:
  - yarn run lint
  - yarn run test:unit
  - yarn run test:integration
notifications:
  email:
    on_success: change
    on_failure: always
